{
 "title": "PostgreSQL Metrics",
 "tags": [
  "postgres",
  "prometheus",
  "database"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Connections Count",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 5 },
   "targets": [
    { "expr": "pg_stat_activity_count" }
   ]
  },
  {
   "title": "Transactions Committed",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[1m])"
    }
   ]
  },
  {
   "title": "Transactions Rolled Back",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback[1m])"
    }
   ]
  },
  {
   "title": "Tuple Inserts",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 5, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_insert[1m])"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks[1m])"
    }
   ]
  },
  {
   "title": "Database Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 10, "w": 12, "h": 5 },
   "targets": [
    { "expr": "pg_database_size_bytes", "legendFormat": "{{datname}}" }
   ]
  }
 ]
}