{
 "title": "Keycloak Metrics",
 "tags": [
  "keycloak",
  "prometheus",
  "authentication"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 5 },
   "targets": [
    { "expr": "keycloak_sessions_active" }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 5 },
   "targets": [
    { "expr": "keycloak_users_count" }
   ]
  },
  {
   "title": "Login Attempts (Total)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 12, "h": 5 },
   "targets": [
    { "expr": "keycloak_login_attempts_total" }
   ]
  },
  {
   "title": "HTTP Requests Count",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 5, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[1m]) / rate(http_server_requests_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Memory Used (Heap)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 10, "w": 12, "h": 5 },
   "targets": [
    { "expr": "base_memory_used_heap_bytes" }
   ]
  }
 ]
}