{
 "title": "Kafka Metrics",
 "tags": [
  "kafka",
  "prometheus",
  "messaging"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Kafka Messages In Per Second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total[1m])"
    }
   ]
  },
  {
   "title": "Kafka Bytes In Per Second",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total[1m])"
    }
   ]
  },
  {
   "title": "Kafka Bytes Out Per Second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total[1m])"
    }
   ]
  },
  {
   "title": "Under-Replicated Partitions",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 5, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 10, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_partitioncount"
    }
   ]
  }
 ]
}