{
 "title": "Spring Boot Full Metrics - Extended",
 "tags": [
  "spring",
  "micrometer",
  "prometheus",
  "medhead"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 3 },
   "targets": [
    {
     "expr": "up{job=~\".*\"}"
    }
   ]
  },
  {
   "title": "Process Uptime (s)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "HTTP Errors Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 3, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m])) by (uri)"
    }
   ]
  },
  {
   "title": "Authentication Errors/sec",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 3, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(spring_security_authentications_seconds_count{error!=\"none\"}[1m])"
    }
   ]
  },
  {
   "title": "Auth Response Time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(spring_security_authentications_seconds_sum[1m]) / rate(spring_security_authentications_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Logback Errors/sec",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(logback_events_total{level=\"error\"}[1m])"
    }
   ]
  },
  {
   "title": "Kafka: Records Sent/sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 13, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_send_total[1m])"
    }
   ]
  },
  {
   "title": "Kafka: Waiting Threads",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 13, "w": 12, "h": 5 },
   "targets": [
    { "expr": "kafka_producer_waiting_threads" }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "disk_free_bytes{path=\"/app/.\"}"
    }
   ]
  },
  {
   "title": "95th Percentile HTTP Latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 18, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[1m]))"
    }
   ]
  },
  {
   "title": "HTTP RPS Total",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 23, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Requests per Speciality",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 23, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/api/hospitals/search.*\"}[1m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}