global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'emergency-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['emergency-back:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]

  - job_name: 'keycloak'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['keycloak:8080']